spring:
  datasource:
    url: jdbc:mysql://localhost:3306/case_study?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: '000000'
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    #开启mybatis驼峰命名规则自动装换
    map-underscore-to-camel-case: true
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印mybatis执行的sql语句
  mapper-locations: classpath*:/mapper/*Dao.xml   #加载mapper.xml文件
  type-aliases-package: com.example.springDemo.domain  # 指定实体类的包路径，这个包下的所有类将进行别名的定义
